project_id = "cwgnlsrqnyugloobrsxz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-verification-email]
verify_jwt = false

[functions.ai-coach-analysis]
verify_jwt = true

[functions.import-google-calendar]
verify_jwt = true
